"""empty message

Revision ID: 09fd4080a1ef
Revises: a96ab56ef756
Create Date: 2022-10-18 20:25:13.511904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fd4080a1ef'
down_revision = 'a96ab56ef756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_sets', 'set_price')
    op.drop_column('cards', 'lowest_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('lowest_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('card_sets', sa.Column('set_price', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
