"""empty message

Revision ID: 218621e667cb
Revises: 78f0c6c9992b
Create Date: 2022-10-09 13:10:18.339647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218621e667cb'
down_revision = '78f0c6c9992b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('cover_img', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'cover_img')
    # ### end Alembic commands ###
