"""empty message

Revision ID: 4d23865f967e
Revises: 09fd4080a1ef
Create Date: 2022-10-18 20:26:14.135037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d23865f967e'
down_revision = '09fd4080a1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'lowest_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('lowest_price', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
