"""empty message

Revision ID: 703f64c825a4
Revises: f34473b19ea0
Create Date: 2022-10-18 20:14:02.680082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703f64c825a4'
down_revision = 'f34473b19ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('lowest_price', sa.Integer(), nullable=True))
    op.drop_constraint('decklists_card_id_fkey', 'decklists', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('decklists_card_id_fkey', 'decklists', 'cards', ['card_id'], ['id'])
    op.drop_column('cards', 'lowest_price')
    # ### end Alembic commands ###
