"""empty message

Revision ID: 78f0c6c9992b
Revises: b83c832862db
Create Date: 2022-10-09 01:37:29.842022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f0c6c9992b'
down_revision = 'b83c832862db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decklists', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decklists', 'quantity')
    # ### end Alembic commands ###
