"""empty message

Revision ID: 95fe9f51e360
Revises: 4d23865f967e
Create Date: 2022-10-18 20:26:35.045604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95fe9f51e360'
down_revision = '4d23865f967e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_sets', 'set_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_sets', sa.Column('set_price', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
