"""empty message

Revision ID: 96e3c4a031e8
Revises: 04073cb2c467
Create Date: 2022-10-18 20:31:06.800909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e3c4a031e8'
down_revision = '04073cb2c467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_sets', 'set_price')
    op.drop_column('cards', 'lowest_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('lowest_price', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('card_sets', sa.Column('set_price', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
