"""empty message

Revision ID: a96ab56ef756
Revises: ee1c9a61270f
Create Date: 2022-10-18 20:16:16.907546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96ab56ef756'
down_revision = 'ee1c9a61270f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_sets', sa.Column('set_rarity', sa.String(length=500), nullable=True))
    op.drop_column('sets', 'rarity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('rarity', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('card_sets', 'set_rarity')
    # ### end Alembic commands ###
