"""empty message

Revision ID: b9ef8dd066d6
Revises: 96e3c4a031e8
Create Date: 2022-10-18 20:32:06.785422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ef8dd066d6'
down_revision = '96e3c4a031e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_sets', sa.Column('set_price', sa.Float(), nullable=True))
    op.add_column('cards', sa.Column('lowest_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'lowest_price')
    op.drop_column('card_sets', 'set_price')
    # ### end Alembic commands ###
