"""empty message

Revision ID: d6895c338a8d
Revises: 95fe9f51e360
Create Date: 2022-10-18 20:26:48.111129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6895c338a8d'
down_revision = '95fe9f51e360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_sets', sa.Column('set_price', sa.String(length=255), nullable=True))
    op.add_column('cards', sa.Column('lowest_price', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'lowest_price')
    op.drop_column('card_sets', 'set_price')
    # ### end Alembic commands ###
