"""empty message

Revision ID: ee1c9a61270f
Revises: 703f64c825a4
Create Date: 2022-10-18 20:15:13.226604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1c9a61270f'
down_revision = '703f64c825a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_sets', sa.Column('set_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_sets', 'set_price')
    # ### end Alembic commands ###
